#!/usr/bin/env php

<?php

require(__DIR__ . '/vendor/autoload.php');

$fileName = 'count';
$path     = __DIR__ . '/temp';
$result   = (new soulrogi\directoryCountSum\DirectoryCountSum($fileName, $path))->getResult();

echo 'Сумма чисел в файлах "' . $fileName . '", равна ' . $result . PHP_EOL;
